// Country name to flag emoji mapping
const countryToFlag: Record<string, string> = {
  'United States': '🇺🇸',
  'Canada': '🇨🇦',
  'United Kingdom': '🇬🇧',
  'Germany': '🇩🇪',
  'France': '🇫🇷',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Poland': '🇵🇱',
  'Czech Republic': '🇨🇿',
  'Slovakia': '🇸🇰',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Bulgaria': '🇧🇬',
  'Greece': '🇬🇷',
  'Croatia': '🇭🇷',
  'Slovenia': '🇸🇮',
  'Estonia': '🇪🇪',
  'Latvia': '🇱🇻',
  'Lithuania': '🇱🇹',
  'Ireland': '🇮🇪',
  'Portugal': '🇵🇹',
  'Luxembourg': '🇱🇺',
  'Iceland': '🇮🇸',
  'Malta': '🇲🇹',
  'Cyprus': '🇨🇾',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'China': '🇨🇳',
  'Taiwan': '🇹🇼',
  'Hong Kong': '🇭🇰',
  'Singapore': '🇸🇬',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Malaysia': '🇲🇾',
  'Indonesia': '🇮🇩',
  'Philippines': '🇵🇭',
  'India': '🇮🇳',
  'Pakistan': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Sri Lanka': '🇱🇰',
  'Nepal': '🇳🇵',
  'Bhutan': '🇧🇹',
  'Myanmar': '🇲🇲',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
  'Mongolia': '🇲🇳',
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'Fiji': '🇫🇯',
  'Papua New Guinea': '🇵🇬',
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Colombia': '🇨🇴',
  'Venezuela': '🇻🇪',
  'Ecuador': '🇪🇨',
  'Bolivia': '🇧🇴',
  'Paraguay': '🇵🇾',
  'Uruguay': '🇺🇾',
  'Guyana': '🇬🇾',
  'Suriname': '🇸🇷',
  'French Guiana': '🇬🇫',
  'Mexico': '🇲🇽',
  'Guatemala': '🇬🇹',
  'Belize': '🇧🇿',
  'El Salvador': '🇸🇻',
  'Honduras': '🇭🇳',
  'Nicaragua': '🇳🇮',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Cuba': '🇨🇺',
  'Jamaica': '🇯🇲',
  'Haiti': '🇭🇹',
  'Dominican Republic': '🇩🇴',
  'Puerto Rico': '🇵🇷',
  'Trinidad and Tobago': '🇹🇹',
  'Barbados': '🇧🇧',
  'Grenada': '🇬🇩',
  'Saint Lucia': '🇱🇨',
  'Saint Vincent and the Grenadines': '🇻🇨',
  'Antigua and Barbuda': '🇦🇬',
  'Saint Kitts and Nevis': '🇰🇳',
  'Dominica': '🇩🇲',
  'Bahamas': '🇧🇸',
  'Cape Verde': '🇨🇻',
  'South Africa': '🇿🇦',
  'Nigeria': '🇳🇬',
  'Kenya': '🇰🇪',
  'Uganda': '🇺🇬',
  'Tanzania': '🇹🇿',
  'Ethiopia': '🇪🇹',
  'Somalia': '🇸🇴',
  'Sudan': '🇸🇩',
  'Egypt': '🇪🇬',
  'Libya': '🇱🇾',
  'Tunisia': '🇹🇳',
  'Algeria': '🇩🇿',
  'Morocco': '🇲🇦',
  'Mauritania': '🇲🇷',
  'Senegal': '🇸🇳',
  'Gambia': '🇬🇲',
  'Guinea-Bissau': '🇬🇼',
  'Guinea': '🇬🇳',
  'Sierra Leone': '🇸🇱',
  'Liberia': '🇱🇷',
  'Ivory Coast': '🇨🇮',
  'Ghana': '🇬🇭',
  'Togo': '🇹🇬',
  'Benin': '🇧🇯',
  'Burkina Faso': '🇧🇫',
  'Mali': '🇲🇱',
  'Niger': '🇳🇪',
  'Chad': '🇹🇩',
  'Central African Republic': '🇨🇫',
  'Cameroon': '🇨🇲',
  'Equatorial Guinea': '🇬🇶',
  'Gabon': '🇬🇦',
  'Republic of the Congo': '🇨🇬',
  'Democratic Republic of the Congo': '🇨🇩',
  'Angola': '🇦🇴',
  'Zambia': '🇿🇲',
  'Zimbabwe': '🇿🇼',
  'Botswana': '🇧🇼',
  'Namibia': '🇳🇦',
  'Lesotho': '🇱🇸',
  'Eswatini': '🇸🇿',
  'Mozambique': '🇲🇿',
  'Madagascar': '🇲🇬',
  'Mauritius': '🇲🇺',
  'Seychelles': '🇸🇨',
  'Comoros': '🇰🇲',
  'Mayotte': '🇾🇹',
  'Reunion': '🇷🇪',
  'Djibouti': '🇩🇯',
  'Eritrea': '🇪🇷',
  'Burundi': '🇧🇮',
  'Rwanda': '🇷🇼',
  'Malawi': '🇲🇼',
  'Russia': '🇷🇺',
  'Ukraine': '🇺🇦',
  'Belarus': '🇧🇾',
  'Moldova': '🇲🇩',
  'Georgia': '🇬🇪',
  'Armenia': '🇦🇲',
  'Azerbaijan': '🇦🇿',
  'Kazakhstan': '🇰🇿',
  'Uzbekistan': '🇺🇿',
  'Turkmenistan': '🇹🇲',
  'Kyrgyzstan': '🇰🇬',
  'Tajikistan': '🇹🇯',
  'Afghanistan': '🇦🇫',
  'Iran': '🇮🇷',
  'Iraq': '🇮🇶',
  'Syria': '🇸🇾',
  'Lebanon': '🇱🇧',
  'Jordan': '🇯🇴',
  'Israel': '🇮🇱',
  'Palestine': '🇵🇸',
  'Saudi Arabia': '🇸🇦',
  'Yemen': '🇾🇪',
  'Oman': '🇴🇲',
  'United Arab Emirates': '🇦🇪',
  'Qatar': '🇶🇦',
  'Bahrain': '🇧🇭',
  'Kuwait': '🇰🇼',
  'Turkey': '🇹🇷',
  'Unknown': '🌍'
};

/**
 * Converts a country name to its corresponding flag emoji
 * @param countryName - The name of the country
 * @returns The flag emoji for the country, or 🌍 for unknown countries
 */
export function getCountryFlag(countryName: string): string {
  return countryToFlag[countryName] || '🌍';
} 